### ISSUE TITLE
KRC20 token icon in API responses should be a hyperlink instead of a base64 image

### ISSUE THREAD

**Issue by trinhdn97** [kardiachain/kardia-explorer-backend#109]
# Prerequisites

Current responses of internal transactions, KRC20 token info and holders API return token logo in base64 format. Because average size of a icon is about `100kB`, API responses are very heavy. We should upload the token logo to some online hosts and store/return the hyperlink of the logo only.

**Comment by ngdlong91** [comment]
@AjackTi : Please provide new API's response

**Comment by AjackTi** [comment]
- Current response: Inserting, Updating the field logo with format base 64 in both table contracts and addresses
- New response: Inserting, Updating the field logo with a link saved in the S3 AWS in both table contracts and addresses

Affected API:
+ Insert contract, address (/api/v1/contracts)
+ Update contract, address (/api/v1/contracts)
