### ISSUE TITLE
Sort addresses list function wrong

### ISSUE THREAD

**Issue by ngdlong91** [kardiachain/kardia-explorer-backend#74]
# Expected Behavior

List account should sort DESC by balance

# Current Behavior

List account sometime return wrong list 

Debug information:

Current we convert balance from string > float64, look like balance cannot convert to float64, so sort function return wrong list.

**Comment by johnnypeck** [comment]
Has this been fixed? I searched for what you described but it's tedious to find what you are referring to. File and line or func would be helpful. Perhaps it's time for issue/pull-request guidelines to help. I can set that up if it's useful to the project. Let me know. Thanks!

**Comment by ngdlong91** [comment]
@johnnypeck : It was fixed. Sorry for late response. And sure, we looking for any contribution from the community, and so much appreciated if any. Feel free to PM me or create issues with your suggestion/proposal.

Thanks

**Comment by ngdlong91** [comment]
Closed.
